spring.application.name=faturamentos
# Define o tamanho máximo de um único arquivo (ex: 50MB)
spring.servlet.multipart.max-file-size=50MB

# Define o tamanho máximo total de uma única requisição/lote (ex: 100MB)
spring.servlet.multipart.max-request-size=100MB
server.port=8081
# Tokens do Tiny ERP para as novas lojas
tiny.loja1.token=8817bd12f4fa0a9f65b623a9db49170d0508c49b7e4bb7484f9bf283da0aedb1
tiny.loja2.token=9d945efbac1018600098662fe89f72508a9e7ded9aee008ca606709534e10b96
